services:
  system-tickets-back:
    build: .
    container_name: system-tickets-back
    restart: unless-stopped
    expose:
      - "8007"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.system-tickets-back.entrypoints=websecure"
      - "traefik.http.routers.system-tickets-back.tls=true"

      - "traefik.http.routers.system-tickets-back.rule=Host(`system-tickets.kobrax.art`) && PathPrefix(`/system-tickets`)"

      - "traefik.http.middlewares.system-tickets-strip.stripprefix.prefixes=/system-tickets"
      - "traefik.http.routers.system-tickets-back.middlewares=system-tickets-strip"

      - "traefik.http.services.system-tickets-back.loadbalancer.server.port=8007"